# Generated by Django 4.2.7 on 2025-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['store', 'day_of_week'], name='uptime_moni_store_i_936a75_idx'),
        ),
        migrations.AddIndex(
            model_name='businesshours',
            index=models.Index(fields=['day_of_week'], name='uptime_moni_day_of__1de357_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='uptime_moni_status_2a6b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='uptime_moni_created_41efb3_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='uptime_moni_status_15ac58_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['timezone_str'], name='uptime_moni_timezon_f8ee78_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['timestamp_utc'], name='uptime_moni_timesta_dd7127_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['status'], name='uptime_moni_status_b940f1_idx'),
        ),
        migrations.AddIndex(
            model_name='storestatus',
            index=models.Index(fields=['store', 'status', 'timestamp_utc'], name='uptime_moni_store_i_6ba01f_idx'),
        ),
    ]
